version: '3'
services:
  sormas:
    links: 
      - postgres
    image: hzibraunschweig/sormas-application:${SORMAS_VERSION}
    environment:
      - SORMAS_POSTGRES_USER=${SORMAS_POSTGRES_USER}
      - SORMAS_POSTGRES_PASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - SORMAS_SERVER_URL=${SORMAS_SERVER_URL}
      - PGPASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
    volumes:
      - ${SORMAS_PATH}/sormas-backup:/root/deploy/sormas/backup
      - ${SORMAS_PATH}/sormas-web:/opt/domains
  postgres:
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    image: hzibraunschweig/sormas-postgres:${SORMAS_VERSION}
    environment:
      - POSTGRES_PASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - POSTGRES_USER=${SORMAS_POSTGRES_USER}
    volumes:
      - ${SORMAS_PATH}/psqldata:/var/lib/postgresql/data
  apache2:
    links:
      - sormas
    depends_on:
      - sormas
    image: hzibraunschweig/sormas-apache2:${SORMAS_VERSION}
    environment:
      - SORMAS_SERVER_URL=${SORMAS_SERVER_URL}
    volumes:
      - ./apache/certs/:/usr/local/apache2/certs/
    ports:
      - "80:80"
      - "443:443"
