version: '2.2'
services:
  sormas:
    restart: unless-stopped
    links:
      - postgres
      - mail
    image: hzibraunschweig/sormas-application:${SORMAS_VERSION}
    environment:
      - SORMAS_POSTGRES_USER=${SORMAS_POSTGRES_USER}
      - SORMAS_POSTGRES_PASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - SORMAS_SERVER_URL=${SORMAS_SERVER_URL}
      - DB_HOST=${DB_HOST}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DB_NAME=${DB_NAME}
      - DB_NAME_AUDIT=${DB_NAME_AUDIT}
      - SMTP_HOST=mail
      - SMTP_USE_STARTTLS=false
      - SMTP_PORT=25
      - SMTP_LOCALHOST=
      - SMTP_USER=
      - SMTP_PASSWORD=
      - EMAIL_SENDER_ADDRESS=${EMAIL_SENDER_ADDRESS}
      - EMAIL_SENDER_NAME=${EMAIL_SENDER_NAME}
      - EMAIL_ERROR_TO=${EMAIL_ERROR_TO}
      - SORMAS_VERSION=${SORMAS_VERSION}
      - LOCALE=${LOCALE}
      - EPIDPREFIX=${EPIDPREFIX}
      - SEPARATOR=${SEPARATOR}
      - LATITUDE=${LATITUDE}
      - LONGITUDE=${LONGITUDE}
      - TZ=${TZ}
      - JVM_MAX=${APPSERVER_JVM_MAX}
      - GEO_UUID=${GEO_UUID}
    depends_on:
      - postgres
    volumes:
      - ${SORMAS_PATH}/custom:/opt/sormas/custom
      - ${SORMAS_PATH}/temp:/opt/sormas/temp
    cpus: ${APPSERVER_CPUS}
    mem_limit: ${APPSERVER_MEM}
    mem_reservation: ${APPSERVER_MEM_RESERVED}
  postgres:
    restart: unless-stopped
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    image: hzibraunschweig/sormas-postgres:${SORMAS_VERSION}
    environment:
      - POSTGRES_PASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - DB_NAME=sormas
      - DB_NAME_AUDIT=sormas_audit
      - SORMAS_POSTGRES_PASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - SORMAS_POSTGRES_USER=${SORMAS_POSTGRES_USER}
      - TZ=${TZ}
    volumes:
      - ${SORMAS_PATH}/psqldata:/var/lib/postgresql/data
      - ${SORMAS_PATH}/temp:/opt/sormas/temp
    ports:
      - "5432:5432"
    cpus: ${DB_CPUS}
    mem_limit: ${DB_MEM}
    mem_reservation: ${DB_MEM_RESERVED}
  pg_dump:
    restart: unless-stopped
    image: hzibraunschweig/sormas-pg-dump:${SORMAS_VERSION}
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=sormas
      - DB_NAME_AUDIT=sormas_audit
      - PGPASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - SORMAS_POSTGRES_USER=${SORMAS_POSTGRES_USER}
      - TZ=${TZ}
      - MIN=15,45 # Twice the hour on 15 and 45 (use crontab notation)
      - HOUR= # Keep empty for every hour. Use crontab notation otherwise
      - KEEP=1 # keep db dumps for one day in backup folder
    volumes:
      - /backup:/var/opt/db_dumps
    cpus: ${DB_DUMP_CPUS}
    mem_limit: ${DB_DUMP_MEM}
    mem_reservation: ${DB_DUMP_MEM_RESERVED}
  apache2:
    restart: unless-stopped
    links:
      - sormas
    depends_on:
      - sormas
    image: hzibraunschweig/sormas-apache2:${SORMAS_VERSION}
    environment:
      - SORMAS_SERVER_URL=${SORMAS_SERVER_URL}
      - TZ=${TZ}
    volumes:
      - ./apache2/certs:/usr/local/apache2/certs
    ports:
      - "80:80"
      - "443:443"
    cpus: ${WEBSERVER_CPUS}
    mem_limit: ${WEBSERVER_MEM}
    mem_reservation: ${WEBSERVER_MEM_RESERVED}
  mail:
    image: hzibraunschweig/sormas-mail:${SORMAS_VERSION}
    links:
      - example-mail-recipient
    restart: unless-stopped
    environment:
      - MAILNAME=${SMTP_LOCALHOST}
      - RELAY_HOST=${SMTP_HOST}
      - RELAY_PORT=${SMTP_PORT}
      - RELAY_USERNAME=${SMTP_USER}
      - RELAY_PASSWORD=${SMTP_PASSWORD}
    cpus: ${MAIL_CPUS}
    mem_limit: ${MAIL_MEM}
    mem_reservation: ${MAIL_MEM_RESERVED}
  example-mail-recipient:
    image: marvambass/versatile-postfix
    restart: unless-stopped
    environment:
      - ALIASES=postmaster:root;hostmaster:root;webmaster:root;admin:root
      - DISABLE_DKIM=true
    command: example-mail-recipient ${SMTP_USER}:${SMTP_PASSWORD}
