version: '3'
services:
  sormas:
    build:
      context: sormas/.
      args:
        SORMAS_URL: ${SORMAS_URL}
    environment:
      - SORMAS_POSTGRES_USER=${SORMAS_POSTGRES_USER}
      - SORMAS_POSTGRES_PASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - PGPASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
    ports:
      - "6080:6080"
  postgres:
    build: postgres/.
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    environment:
      - POSTGRES_PASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - POSTGRES_USER=${SORMAS_POSTGRES_USER}
    volumes:
      - psqldata:/var/lib/postgresql/data
  apache2:
    build:
      context: apache2/.
    links:
      - sormas
    depends_on:
      - sormas
    environment:
      - SORMAS_SERVER_URL=${SORMAS_SERVER_URL}
    volumes:
      - apache2_www:/var/www/
      - apache2_local:/usr/local/apache2/
      - ./apache2/certs/:/usr/local/apache2/certs/
    ports:
      - "80:80"
      - "443:443"

volumes:
  psqldata:
  apache2_www:
  apache2_local:
