version: '3'
services:
  sormas:
    image: hzibraunschweig/sormas-application:latest
    environment:
      - SORMAS_POSTGRES_USER=${SORMAS_POSTGRES_USER}
      - SORMAS_POSTGRES_PASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - SORMAS_SERVER_URL=${SORMAS_SERVER_URL}
      - PGPASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
    volumes:
      - sormas-backup:/root/deploy/sormas/backup
      - sormas-web:/opt/domains
  postgres:
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    image: hzibraunschweig/sormas-postgres:latest
    environment:
      - POSTGRES_PASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - POSTGRES_USER=${SORMAS_POSTGRES_USER}
    volumes:
      - psqldata:/var/lib/postgresql/data
  apache2:
    links:
      - sormas
    depends_on:
      - sormas
    image: hzibraunschweig/sormas-apache2:latest
    environment:
      - SORMAS_SERVER_URL=${SORMAS_SERVER_URL}
    volumes:
      - ./apache2/certs/:/usr/local/apache2/certs/
    ports:
      - "80:80"
      - "443:443"

volumes:
  psqldata:
  sormas-backup:
  sormas-web:

