version: '3'
services:
  sormas:
    build:
      context: sormas/.
      args:
        SORMAS_URL: ${SORMAS_URL}
    image: docker.netzlink.com/sormas/sormas:vm1.0
    environment:
      - SORMAS_POSTGRES_USER=${SORMAS_POSTGRES_USER}
      - SORMAS_POSTGRES_PASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - SORMAS_SERVER_URL=${SORMAS_SERVER_URL}
      - PGPASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
    volumes:
      - sormas-backup:/root/deploy/sormas/backup
      - sormas-web:/opt/domains
    ports:
      - "6080:6080"
  postgres:
    build: postgres/.
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    image: docker.netzlink.com/sormas/postgres:vm1.0
    environment:
      - POSTGRES_PASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - POSTGRES_USER=${SORMAS_POSTGRES_USER}
    volumes:
      - psqldata:/var/lib/postgresql/data
    

volumes:
  psqldata:
  sormas-backup:
  sormas-web:
