version: '3'
services:
  sormas:
    build:
      context: sormas/.
      args:
        - SORMAS_POSTGRES_USER=${SORMAS_POSTGRES_USER}
        - SORMAS_POSTGRES_PASSWORD=${SORMAS_POSTGRES_PASSWORD}
        - SORMAS_SERVER_URL=${SORMAS_SERVER_URL}
        - DB_HOST=${DB_HOST}
        - DOMAIN_NAME=${DOMAIN_NAME}
        - DB_NAME=${DB_NAME}
        - DB_NAME_AUDIT=${DB_NAME_AUDIT}
        - MAIL_HOST=${MAIL_HOST}
        - MAIL_FROM=${MAIL_FROM}
        - JVM_MAX=${JVM_MAX}
        - SORMAS_VERSION=${SORMAS_VERSION}
    image: docker.netzlink.com/sormas/sormas:vm1.2
    environment:
      - SORMAS_POSTGRES_USER=${SORMAS_POSTGRES_USER}
      - SORMAS_POSTGRES_PASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - PGPASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - SORMAS_SERVER_URL=${SORMAS_SERVER_URL}
      - DB_HOST=${DB_HOST}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DB_NAME=${DB_NAME}
      - DB_NAME_AUDIT=${DB_NAME_AUDIT}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_FROM=${MAIL_FROM}
      - JVM_MAX=${JVM_MAX}
      - SORMAS_VERSION=${SORMAS_VERSION}
      - LOCALE=${LOCALE}
      - EPIDPREFIX=${EPIDPREFIX}
      - SEPARATOR=${SEPARATOR}
      - EMAIL_SENDER_ADDRESS=${EMAIL_SENDER_ADDRESS}
      - EMAIL_SENDER_NAME=${EMAIL_SENDER_NAME}
      - LATITUDE=${LATITUDE}
      - LONGITUDE=${LONGITUDE}
    volumes:
      - sormas-backup:/root/deploy/sormas/backup
    depends_on:
      - postgres
  postgres:
    build: postgres/.
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    image: docker.netzlink.com/sormas/postgres:vm1.2
    environment:
      - POSTGRES_PASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - DB_NAME=sormas
      - DB_NAME_AUDIT=sormas_audit
      - SORMAS_POSTGRES_PASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - SORMAS_POSTGRES_USER=${SORMAS_POSTGRES_USER}
    volumes:
      - psqldata:/var/lib/postgresql/data
  apache2:
    build:
      context: apache2/.
      args:
        - SORMAS_SERVER_URL=${SORMAS_SERVER_URL}
        - SORMAS_VERSION=${SORMAS_VERSION}
    links:
      - sormas
    depends_on:
      - sormas
    image: docker.netzlink.com/sormas/apache2:vm1.2
    environment:
      - SORMAS_SERVER_URL=${SORMAS_SERVER_URL}
    volumes:
      - ./apache2/certs:/usr/local/apache2/certs
    ports:
      - "80:80"
      - "443:443"

volumes:
  psqldata:
  sormas-backup:
