version: '3'
services:
  sormas:
    links: 
      - postgres
    image: hzibraunschweig/sormas-application:${SORMAS_VERSION}
    environment:
      - SORMAS_POSTGRES_USER=${SORMAS_POSTGRES_USER}
      - SORMAS_POSTGRES_PASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - SORMAS_SERVER_URL=${SORMAS_SERVER_URL}
      - DB_HOST=${DB_HOST}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DB_NAME=${DB_NAME}
      - DB_NAME_AUDIT=${DB_NAME_AUDIT}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_FROM=${MAIL_FROM}
      - JVM_MAX=${JVM_MAX}
      - SORMAS_VERSION=${SORMAS_VERSION}
      - LOCALE=${LOCALE}
      - EPIDPREFIX=${EPIDPREFIX}
      - SEPARATOR=${SEPARATOR}
      - EMAIL_SENDER_ADDRESS=${EMAIL_SENDER_ADDRESS}
      - EMAIL_SENDER_NAME=${EMAIL_SENDER_NAME}
      - LATITUDE=${LATITUDE}
      - LONGITUDE=${LONGITUDE}
    volumes:
      - ${SORMAS_PATH}/sormas-backup:/root/deploy/sormas/backup
    depends_on:
      - postgres
  postgres:
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    image: hzibraunschweig/sormas-postgres:${SORMAS_VERSION}
    environment:
      - POSTGRES_PASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - DB_NAME=sormas
      - DB_NAME_AUDIT=sormas_audit
      - SORMAS_POSTGRES_PASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - SORMAS_POSTGRES_USER=${SORMAS_POSTGRES_USER}
    volumes:
      - ${SORMAS_PATH}/psqldata:/var/lib/postgresql/data
  apache2:
    links:
      - sormas
    depends_on:
      - sormas
    image: hzibraunschweig/sormas-apache2:${SORMAS_VERSION}
    environment:
      - SORMAS_SERVER_URL=${SORMAS_SERVER_URL}
    volumes:
      - ./apache2/certs:/usr/local/apache2/certs
    ports:
      - "80:80"
      - "443:443"

