version: '3'
services:
  sormas:
    build:
      context: sormas/.
      args:
        SORMAS_URL: ${SORMAS_URL}
        SORMAS_POSTGRES_USER: ${SORMAS_POSTGRES_USER}
        SORMAS_POSTGRES_PASSWORD: ${SORMAS_POSTGRES_PASSWORD}
    ports:
      - "6080:6080"
  postgres:
    build: postgres/.
    environment:
      - POSTGRES_PASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - POSTGRES_USER=${SORMAS_POSTGRES_USER}
    volumes:
      - psqldata:/var/lib/postgresql/data
  apache2:
    build:
      context: apache2/.
      args:
        SORMAS_SERVER_URL: ${SORMAS_SERVER_URL}   
    volumes:
      - apache2_www:/var/www/
      - apache2_etc:/etc/httpd/
    ports:
      - "80:80"
      - "443:443"

volumes:
  psqldata:
  apache2_www:
  apache2_etc:
