version: '3'
services:
  sormas:
    build:
      context: sormas/.
      args:
        SORMAS_URL: ${SORMAS_URL}
        SORMAS_POSTGRES_USER: ${SORMAS_POSTGRES_USER}
        SORMAS_POSTGRES_PASSWORD: ${SORMAS_POSTGRES_PASSWORD}
    ports:
      - "6080:6080"
  postgres:
    build: postgres/.
    environment:
      - POSTGRES_PASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - POSTGRES_USER=${SORMAS_POSTGRES_USER}
    volumes:
      - psqldata:/var/lib/postgresql/data

volumes:
  psqldata:
