version: '3'
services:
  sormas:
    build: 
      context: sormas/.
      args: 
        SORMAS_URL: ${SORMAS_URL}
    ports:
      - "6080:6080"
  postgres:
    build: postgres/.
    environment: 
      - POSTGRES_PASSWORD=${SORMAS_POSTGRES_PASSWORD}
    